OBJECT = {
    "backpack": "backpack",
    "backpack_dog": "backpack",
    "bear_plushie": "stuffed animal",
    "berry_bowl": "bowl",
    "can": "can",
    "candle": "candle",
    "clock": "clock",
    "colorful_sneaker": "sneaker",
    "duck_toy": "toy",
    "fancy_boot": "boot",
    "grey_sloth_plushie": "stuffed animal",
    "monster_toy": "toy",
    "pink_sunglasses": "glasses",
    "poop_emoji": "toy",
    "rc_car": "toy",
    "red_cartoon": "cartoon",
    "robot_toy": "toy",
    "shiny_sneaker": "sneaker",
    "teapot": "teapot",
    "vase": "vase",
    "wolf_plushie": "stuffed animal"
}

LIVE_OBJECT = {
    "cat": "cat",
    "cat2": "cat",
    "dog": "dog",
    "dog2": "dog",
    "dog3": "dog",
    "dog5": "dog",
    "dog6": "dog",
    "dog7": "dog",
    "dog8": "dog",
}

OBJECT_PROMPTS = [
    'a {} in the jungle',
    'a {} in the snow',
    'a {} on the beach',
    'a {} on a cobblestone street',
    'a {} on top of pink fabric',
    'a {} on top of a wooden floor',
    'a {} with a city in the background',
    'a {} with a mountain in the background',
    'a {} with a blue house in the background',
    'a {} on top of a purple rug in a forest',
    'a {} with a wheat field in the background',
    'a {} with a tree and autumn leaves in the background',
    'a {} with the Eiffel Tower in the background',
    'a {} floating on top of water',
    'a {} floating in an ocean of milk',
    'a {} on top of green grass with sunflowers around it',
    'a {} on top of a mirror',
    'a {} on top of the sidewalk in a crowded street',
    'a {} on top of a dirt road',
    'a {} on top of a white rug',
    'a red {}',
    'a purple {}',
    'a shiny {}',
    'a wet {}',
    'a cube shaped {}'
]

LIVE_OBJECT_PROMPTS = [
    'a {} in the jungle',
    'a {} in the snow',
    'a {} on the beach',
    'a {} on a cobblestone street',
    'a {} on top of pink fabric',
    'a {} on top of a wooden floor',
    'a {} with a city in the background',
    'a {} with a mountain in the background',
    'a {} with a blue house in the background',
    'a {} on top of a purple rug in a forest',
    'a {} wearing a red hat',
    'a {} wearing a santa hat',
    'a {} wearing a rainbow scarf',
    'a {} wearing a black top hat and a monocle',
    'a {} in a chef outfit',
    'a {} in a firefighter outfit',
    'a {} in a police outfit',
    'a {} wearing pink glasses',
    'a {} wearing a yellow shirt',
    'a {} in a purple wizard outfit',
    'a red {}',
    'a purple {}',
    'a shiny {}',
    'a wet {}',
    'a cube shaped {}'
]

SODA_OBJECT_PROMPTS = [
    'Same {}, but in the jungle',
    'Same {}, but in the snow',
    'Same {}, but on the beach',
    'Same {}, but on a cobblestone street',
    'Same {}, but on top of pink fabric',
    'Same {}, but on top of a wooden floor',
    'Same {}, but with a city in the background',
    'Same {}, but with a mountain in the background',
    'Same {}, but with a blue house in the background',
    'Same {}, but on top of a purple rug in a forest',
    'Same {}, but with a wheat field in the background',
    'Same {}, but with a tree and autumn leaves in the background',
    'Same {}, but with the Eiffel Tower in the background',
    'Same {}, but floating on top of water',
    'Same {}, but floating in an ocean of milk',
    'Same {}, but on top of green grass with sunflowers around it',
    'Same {}, but on top of a mirror',
    'Same {}, but on top of the sidewalk in a crowded street',
    'Same {}, but on top of a dirt road',
    'Same {}, but on top of a white rug',
    'Same {}, but red',
    'Same {}, but purple',
    'Same {}, but shiny',
    'Same {}, but wet',
    'Same {}, but cube shaped'
]

SODA_LIVE_OBJECT_PROMPTS = [
    'Same {}, but in the jungle',
    'Same {}, but in the snow',
    'Same {}, but on the beach',
    'Same {}, but on a cobblestone street',
    'Same {}, but on top of pink fabric',
    'Same {}, but on top of a wooden floor',
    'Same {}, but with a city in the background',
    'Same {}, but with a mountain in the background',
    'Same {}, but with a blue house in the background',
    'Same {}, but on top of a purple rug in a forest',
    'Same {}, but wearing a red hat',
    'Same {}, but wearing a santa hat',
    'Same {}, but wearing a rainbow scarf',
    'Same {}, but wearing a black top hat and a monocle',
    'Same {}, but in a chef outfit',
    'Same {}, but in a firefighter outfit',
    'Same {}, but in a police outfit',
    'Same {}, but wearing pink glasses',
    'Same {}, but wearing a yellow shirt',
    'Same {}, but in a purple wizard outfit',
    'Same {}, but red',
    'Same {}, but purple',
    'Same {}, but shiny',
    'Same {}, but wet',
    'Same {}, but cube shaped'
]